
'use client';

import * as React from 'react';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';

import { Button } from '@/components/ui/button';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import { Input } from '@/components/ui/input';
import { useToast } from '@/hooks/use-toast';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './ui/select';
import type { Company } from '@/types';

const companyFormSchema = z.object({
  fieldName: z.string().min(2, 'Field name must be at least 2 characters.'),
  accountNumber: z.string().min(4, 'Account number must be at least 4 characters.'),
  branch: z.string({ required_error: 'Please select a branch.' }),
});

type CompanyFormValues = z.infer<typeof companyFormSchema>;

// In a real app, this would be fetched from your API
const MOCK_BRANCHES = [
  { id: '1', name: 'Downtown Branch' },
  { id: '2', name: 'Uptown Branch' },
  { id: '3', name: 'Westside Branch' },
  { id: '4', name: 'Eastside Branch' },
  { id: '5', name: 'South Branch' },
];


export function AddCompanyForm({ 
  setOpen, 
  onAddCompany 
}: { 
  setOpen: (open: boolean) => void,
  onAddCompany: (company: Company) => void 
}) {
  const { toast } = useToast();
  const form = useForm<CompanyFormValues>({
    resolver: zodResolver(companyFormSchema),
    defaultValues: {
      fieldName: '',
      accountNumber: '',
    },
  });

  function onSubmit(data: CompanyFormValues) {
    const newCompany: Company = {
      id: new Date().toISOString(), // This would be generated by the server
      ...data,
      approved: false,
      status: 'Pending',
      logoUrl: 'https://placehold.co/40x40.png',
      hint: 'logo new'
    };
    onAddCompany(newCompany);
    toast({
      title: 'Company Submitted for Approval',
      description: `${data.fieldName} has been sent for verification.`,
    });
    setOpen(false);
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
        <FormField
          control={form.control}
          name="fieldName"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Field Name</FormLabel>
              <FormControl>
                <Input placeholder="Innovate Inc." {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="accountNumber"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Account Number</FormLabel>
              <FormControl>
                <Input placeholder="ACC12345" {...field} />
              </FormControl>
              <FormMessage />
            </FormItem>
          )}
        />
        <FormField
          control={form.control}
          name="branch"
          render={({ field }) => (
            <FormItem>
              <FormLabel>Branch</FormLabel>
              <Select onValueChange={field.onChange} defaultValue={field.value}>
                <FormControl>
                  <SelectTrigger>
                    <SelectValue placeholder="Select a branch" />
                  </SelectTrigger>
                </FormControl>
                <SelectContent>
                  {MOCK_BRANCHES.map(branch => (
                     <SelectItem key={branch.id} value={branch.name}>{branch.name}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <FormMessage />
            </FormItem>
          )}
        />
        <div className="flex justify-end gap-2 pt-4">
            <Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button>
            <Button type="submit">Add Company</Button>
        </div>
      </form>
    </Form>
  );
}
